name: flutter_zoom_checker
description: A plugin to check if display is zoomed
version: 0.0.1
homepage: https://bnsaed.com/
repository: https://github.com/binSaed/flutter_zoom_checker
issue_tracker: https://github.com/binSaed/flutter_zoom_checker/issues


topics:
  - ios
  - zoom
  - display

environment:
  sdk: '>=3.1.4 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: FlutterZoomCheckerPlugin